server:
  port: ${SERVER_PORT:8040}

spring:
  application:
    name: Apli-Servi
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/ani}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

minio:
  endpoint: ${MINIO_ENDPOINT:http://minio:9000}
  accessKey: ${MINIO_ACCESSKEY:minioadmin}
  secretKey: ${MINIO_SECRETKEY:minio123minio}

security:
  jwt:
    key:
      private: 9414b0f9e189fc39821198d6f8f04a15c38a3efc71843d77673d4e1bbcc8cc72
    user:
      generator: AUTHBAT
    token:
      access-expiration: 3600000
      refresh-expiration: 2592000000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  file:
    name: application.log
