name: CI/CD Backend with Tests and Docker

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.6
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: ani
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/ani
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESSKEY: minioadmin
      MINIO_SECRETKEY: minio123minio
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Wait for Postgres to be ready
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 && break
            echo "Waiting for Postgres to be ready..."
            sleep 2
          done

      # 1️⃣ Ejecutar pruebas unitarias
      - name: Run unit tests
        run: |
          cd Apli-Servi
          chmod +x ./mvnw
          ./mvnw clean test --no-transfer-progress

      # 2️⃣ Ejecutar pruebas de integración
      - name: Run integration tests
        run: |
          cd Apli-Servi
          ./mvnw verify -Pintegration --no-transfer-progress

      # 3️⃣ Compilar y empaquetar backend
      - name: Build package
        run: |
          cd Apli-Servi
          ./mvnw package -DskipTests --no-transfer-progress

      # 4️⃣ Login Docker
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 5️⃣ Construir y subir imagen Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./Apli-Servi
          file: ./Apli-Servi/Dockerfile
          push: true
          tags: freddychura93/cicddockerdiplonadogithubactionsecomercebackend2025
